web:
  build: .  # use web image in current directory
  command: python -u app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/todo  # sync host's current directory with web's todo folder
  links:
    - db  # compose links web to db
db:
  image: mongo:3.0.2  # separate dockerfile